#Elenco technology da utilizzare nel FacetGrid

technology_list = ['Bioenergy and renewable waste',
'Biomass and biogas',
'Combined cycle',
'Concentrated solar power',
'Differently categorized fossil fuels',
'Differently categorized hydro',
'Differently categorized natural gas',
'Differently categorized renewable energy sources',
'Differently categorized solar',
'Differently categorized wind',
'Fossil fuels',
'Gas turbine',
'Geothermal',
'Hard coal',
'Hydro',
'Lignite',
'Marine',
'Mixed fossil fuels',
'Natural gas',
'Non-renewable waste',
'Nuclear',
'Offshore',
'Oil',
'Onshore',
'Other and unknown natural gas',
'Other bioenergy and renewable waste',
'Other fossil fuels',
'Other or unspecified energy sources',
'Photovoltaics',
'Pumped storage',
'Pumped storage with natural inflow',
'Renewable energy sources',
'Reservoir',
'Reservoir including pumped storage',
'Run-of-river',
'Sewage and landfill gas',
'Solar',
'Wind']